name: Leviathan
version: 1.1
main: de.kumo.leviathan.Main
api-version: 1.19
author: Kumo
default-permission: op

commands:
  heal:
    description: simple health and hunger filler

  enderchest:
    description: magic pocket
    aliases: ec

  mute:
    description: mutes someone

  crash:
    description: not very funny

  workbench:
    description: for the crafters
    aliases: wb

  live:
    description: sets a live status on the scoreboard